apiVersion: v1
kind: Service
metadata:
  name: go-grpc
spec:
  type: ClusterIP
  ports:
    - port: 3456
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: go-grpc
