print("pulumi_crds init")
# coding=utf-8
# *** WARNING: this file was generated by crd2pulumi. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_crds.gateway as __gateway
    gateway = __gateway
    import pulumi_crds.meta as __meta
    meta = __meta
else:
    gateway = _utilities.lazy_import('pulumi_crds.gateway')
    meta = _utilities.lazy_import('pulumi_crds.meta')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "crds",
  "mod": "gateway.networking.k8s.io/v1",
  "fqn": "pulumi_crds.gateway.v1",
  "classes": {
   "kubernetes:gateway.networking.k8s.io/v1:GRPCRoute": "GRPCRoute",
   "kubernetes:gateway.networking.k8s.io/v1:GRPCRouteList": "GRPCRouteList",
   "kubernetes:gateway.networking.k8s.io/v1:GRPCRoutePatch": "GRPCRoutePatch",
   "kubernetes:gateway.networking.k8s.io/v1:Gateway": "Gateway",
   "kubernetes:gateway.networking.k8s.io/v1:GatewayClass": "GatewayClass",
   "kubernetes:gateway.networking.k8s.io/v1:GatewayClassList": "GatewayClassList",
   "kubernetes:gateway.networking.k8s.io/v1:GatewayClassPatch": "GatewayClassPatch",
   "kubernetes:gateway.networking.k8s.io/v1:GatewayList": "GatewayList",
   "kubernetes:gateway.networking.k8s.io/v1:GatewayPatch": "GatewayPatch",
   "kubernetes:gateway.networking.k8s.io/v1:HTTPRoute": "HTTPRoute",
   "kubernetes:gateway.networking.k8s.io/v1:HTTPRouteList": "HTTPRouteList",
   "kubernetes:gateway.networking.k8s.io/v1:HTTPRoutePatch": "HTTPRoutePatch"
  }
 },
 {
  "pkg": "crds",
  "mod": "gateway.networking.k8s.io/v1beta1",
  "fqn": "pulumi_crds.gateway.v1beta1",
  "classes": {
   "kubernetes:gateway.networking.k8s.io/v1beta1:Gateway": "Gateway",
   "kubernetes:gateway.networking.k8s.io/v1beta1:GatewayClass": "GatewayClass",
   "kubernetes:gateway.networking.k8s.io/v1beta1:GatewayClassList": "GatewayClassList",
   "kubernetes:gateway.networking.k8s.io/v1beta1:GatewayClassPatch": "GatewayClassPatch",
   "kubernetes:gateway.networking.k8s.io/v1beta1:GatewayList": "GatewayList",
   "kubernetes:gateway.networking.k8s.io/v1beta1:GatewayPatch": "GatewayPatch",
   "kubernetes:gateway.networking.k8s.io/v1beta1:HTTPRoute": "HTTPRoute",
   "kubernetes:gateway.networking.k8s.io/v1beta1:HTTPRouteList": "HTTPRouteList",
   "kubernetes:gateway.networking.k8s.io/v1beta1:HTTPRoutePatch": "HTTPRoutePatch",
   "kubernetes:gateway.networking.k8s.io/v1beta1:ReferenceGrant": "ReferenceGrant",
   "kubernetes:gateway.networking.k8s.io/v1beta1:ReferenceGrantList": "ReferenceGrantList",
   "kubernetes:gateway.networking.k8s.io/v1beta1:ReferenceGrantPatch": "ReferenceGrantPatch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "crds",
  "token": "pulumi:providers:kubernetes",
  "fqn": "pulumi_crds",
  "class": "Provider"
 }
]
"""
)
