apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2022-11-12T19:47:53Z"
  generation: 14
  labels:
    app: nginx
  name: nginx
  resourceVersion: "2931412"
  uid: e73c4c4f-6905-4487-b44d-cb489055487f
spec:
  progressDeadlineSeconds: 600
  replicas: 20
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-11-13T01:33:42+05:30"
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources:
          limits:
            cpu: 500m
            memory: 700M
          requests:
            cpu: 500m
            memory: 700M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 15
  conditions:
  - lastTransitionTime: "2022-11-12T20:05:59Z"
    lastUpdateTime: "2022-11-12T20:05:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2022-11-12T19:47:53Z"
    lastUpdateTime: "2022-11-12T20:06:01Z"
    message: ReplicaSet "nginx-7c7b8996b5" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 14
  readyReplicas: 15
  replicas: 22
  unavailableReplicas: 7
  updatedReplicas: 20
