// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type egressRecvArgs struct {
	_    structs.HostLayout
	Buf  uint64
	Size uint64
}

// loadEgress returns the embedded CollectionSpec for egress.
func loadEgress() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EgressBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load egress: %w", err)
	}

	return spec, err
}

// loadEgressObjects loads egress and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*egressObjects
//	*egressPrograms
//	*egressMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadEgressObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadEgress()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// egressSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressSpecs struct {
	egressProgramSpecs
	egressMapSpecs
	egressVariableSpecs
}

// egressProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressProgramSpecs struct {
	HandleEnter         *ebpf.ProgramSpec `ebpf:"handle_enter"`
	HandleRecvfromEnter *ebpf.ProgramSpec `ebpf:"handle_recvfrom_enter"`
	HandleRecvfromExit  *ebpf.ProgramSpec `ebpf:"handle_recvfrom_exit"`
	HandleSendto        *ebpf.ProgramSpec `ebpf:"handle_sendto"`
}

// egressMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressMapSpecs struct {
	Events       *ebpf.MapSpec `ebpf:"events"`
	RecvfromArgs *ebpf.MapSpec `ebpf:"recvfrom_args"`
}

// egressVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type egressVariableSpecs struct {
}

// egressObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressObjects struct {
	egressPrograms
	egressMaps
	egressVariables
}

func (o *egressObjects) Close() error {
	return _EgressClose(
		&o.egressPrograms,
		&o.egressMaps,
	)
}

// egressMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressMaps struct {
	Events       *ebpf.Map `ebpf:"events"`
	RecvfromArgs *ebpf.Map `ebpf:"recvfrom_args"`
}

func (m *egressMaps) Close() error {
	return _EgressClose(
		m.Events,
		m.RecvfromArgs,
	)
}

// egressVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressVariables struct {
}

// egressPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadEgressObjects or ebpf.CollectionSpec.LoadAndAssign.
type egressPrograms struct {
	HandleEnter         *ebpf.Program `ebpf:"handle_enter"`
	HandleRecvfromEnter *ebpf.Program `ebpf:"handle_recvfrom_enter"`
	HandleRecvfromExit  *ebpf.Program `ebpf:"handle_recvfrom_exit"`
	HandleSendto        *ebpf.Program `ebpf:"handle_sendto"`
}

func (p *egressPrograms) Close() error {
	return _EgressClose(
		p.HandleEnter,
		p.HandleRecvfromEnter,
		p.HandleRecvfromExit,
		p.HandleSendto,
	)
}

func _EgressClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed egress_bpfeb.o
var _EgressBytes []byte
