apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: productmappings.example.com 
spec:
  scope: Namespaced
  group: example.com 
  names:
    kind: ProductMapping
    plural: productmappings
    singular: productmapping
    shortNames:
      - pms
      - pm
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true