name: nginx-infra
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: ../venv
description: A minimal Kubernetes Python Pulumi program
config:
  pulumi:tags:
    value:
      pulumi:template: kubernetes-python
