apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../server
- ../../client
- namespace.yaml

namespace: "stage"

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/environment: stage

commonAnnotations:
 linkerd.io/inject: enabled 

