version: '3'

tasks:
  test:
    deps: # Executes concurrently
      - fmt 
      - vet
    cmds: 
      - go test -count=1 {{.CLI_ARGS}}

  fmt:
    cmds:
      - go fmt ./...

  vet:
    cmds:
      - go vet ./...
