dependencies:
  sqs:
    - name: test-sqs
      dlq: foo
  s3:
    - name: test-s3-bucket 
      versioning: false
    - name: _common
      versioning: true
      encryption: true
      tags:
        config2: true
aws_region: ap-south-1
foo: bar
