dependencies:
  s3:
    - name: test-s3-bucket
      versioning: false
      encrypt_object: false
      allowed: 
      - resource: snape.service
        access:
          - read
          - write
      - resource: locksmith.service
        access: 
          - read
          - write
      tags:
        encrypted: true
        service: genie
    - name: test-s3-bucket-2
      versioning: true
      encrypt_object: true
      tags:
        encrypted: true
