apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  namespace: jenkins
  name: master
spec:
  configurationAsCode:
    configurations: 
      - name: user-configuration
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    basePlugins:
    - name: kubernetes
      version: "3937.vd7b_82db_e347b_"
    - name: workflow-job
      version: "1301.v054d9cea_9593"
    - name: workflow-aggregator
      version: "596.v8c21c963d92d"
    - name: git
      version: "5.0.2"
    - name: job-dsl
      version: "1.83"
    - name: configuration-as-code
      version: "1625.v27444588cc3d"
    - name: kubernetes-credentials-provider
      version: "1.211.vc236a_f5a_2f3c"
    - name: ionicons-api      
      version: "56.v1b_1c8c49374e"
    - name: "ssh-credentials"
      version: "305.v8f4381501156"
    - name: saml
      version: "4.403.v423b_3195a_9ec"
    disableCSRFProtection: false
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.401.1-lts-alpine
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: http
            scheme: HTTP
          initialDelaySeconds: 80
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "1024m"
            memory: 2Gi
          requests:
            cpu: "500m" 
            memory: 2Gi
  seedJobs:
    - id: jenkins-operator
      targets: "cicd/jobs/*.jenkins"
      description: "Jenkins Operator repository"
      repositoryBranch: master
      repositoryUrl: https://github.com/jenkinsci/kubernetes-operator.git
