apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: user-configuration 
data:
  1-system-message.yaml: |
    jenkins:
      systemMessage: "Configuration as Code integration works!!!"
