apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../server

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: go-grpc-client

nameSuffix: -client

patches:
- path: ./patch_service.yaml
  target:
    version: v1
    kind: Service
    name: go-grpc
- path: ./patch_deployment.yaml
  target:
    version: v1
    kind: Deployment
    name: go-grpc

images:
- name: "ghcr.io/msharran/go-grpc"
  newTag: client-1.0.0
