dependencies:
  sqs:
    - name: test-sqs
  s3:
    - name: test-s3-bucket
      labels: 
      - foo
      - bar
      encryption: false
      tags:
        config: true
      authz: 
        bar.service: 
          - read
          - write
        baz.service:
          - read
          - write
    - name: test-s3-bucket-2
      authz: 
        bar.service: 
          - read
          - write
        baz.service:
          - read
          - write

bar: baz
