{{- $fullName := include "go-grpc.clientFullname" . -}}
{{- $svcPort := .Values.clientService.port -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "go-grpc.clientLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "go-grpc.clientSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "go-grpc.clientLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "go-grpc.clientServiceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $fullName }}
          securityContext:
           {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.clientImage.repository }}:{{ .Values.clientImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.clientImage.pullPolicy }}
          args: ["-port={{ .Values.clientService.port }}", "-server-addr={{ include "go-grpc.fullname" . }}:{{ .Values.service.port }}"]
          ports:
            - name: http
              containerPort: {{ .Values.clientService.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /hello
              port: {{ .Values.clientService.port }}
          livenessProbe:
            httpGet:
              path: /hello
              port: {{ .Values.clientService.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
