#!/usr/bin/env ruby

location = "#{ENV['HOME']}/.password-store"
passwords = Dir["#{location}/**/*.gpg"]

grouped = {}

passwords.each do |password|
  pass = password.gsub("#{location}/", '').gsub(".gpg", '')
  first = pass.split('/').first
  grouped[first] = [] unless grouped[first]
  grouped[first] << pass
end

grouped.each do |group, passwords|
  puts "#{group}:"
  passwords.each do |password|
    puts "  #{password}".gsub("#{group}/", '')
  end
end
