{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "go-grpc.clientServiceAccountName" . }}
  labels:
    {{- include "go-grpc.clientLabels" . | nindent 4 }}
  {{- with .Values.clientServiceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.clientServiceAccount.automount }}
{{- end }}
